# ========================================
# ResolveAI Application
# ========================================

spring.application.name=resolveai


# ========================================
# MySQL Configuration
# ========================================

spring.datasource.url=jdbc:mysql://localhost:3306/resolveai_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ========================================
# JPA / Hibernate Configuration
# ========================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ========================================
# MongoDB Configuration
# ========================================

# ========================================
# MongoDB Configuration
# ========================================

spring.mongodb.uri=mongodb://localhost:27017/resolveai_mongo
spring.mongodb.database=resolveai_mongo
# JWT
app.jwt.expiration=86400000
app.jwt.secret=8LHtlK+pLkAU1jrJtLocXE35J4kJS76McTI+1Yhi59k=

# ========================================
# File Upload Configuration
# ========================================

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB

# ========================================
# Spring AI - Ollama
# ========================================

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=qwen2.5:7b